### ISSUE TITLE
Bugs: Registro y Editar perfil

### ISSUE THREAD

**Issue by danielsolartech** [snakone/Antic-s-Code#6]
## Registro
Si la cuenta ya existe no te lo dice, sino que te saca un error de que no se pudo enviar el formulario.

![Registro](https://i.imgur.com/jAK2Pum.png)

## Editar perfil
En pantallas muy pequeñas (O al menos en Firefox con favoritos) no deja ver el botón de "Guardar" y tampoco deja hacer scroll. 

![Editar perfil](https://i.imgur.com/tbAm40n.png).

**Comment by snakone** [comment]
gracias por comentar, estaré al tanto para corregirlo 👍

**Comment by snakone** [comment]
corregido, entrará en la próxima subida
